name: mern-app

services:
  mongo:
    image: mongo:8.0.15
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - mern-app

  api:
    build:
      context    : ./backend
      dockerfile : Dockerfile
    restart  : unless-stopped
    env_file : ./backend/.env
    environment:
      - NODE_ENV=docker
    volumes  :
      - ./backend:/app
      - /app/node_modules
    working_dir: /app
    command: sh -c "if [ ! -d node_modules ] || [ -z \"$(ls -A node_modules 2>/dev/null)\" ]; then npm ci; fi && node config/import-data.js --delete && node config/import-data.js --import && npx nodemon server.js"
    ports:
      - 4000:4000
    networks:
      - mern-app
    depends_on:
      - mongo

  frontend:
    image: node:22-alpine
    restart  : unless-stopped
    volumes  :
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    ports   :
      - 5173:5173
    networks:
      - mern-app
    command: sh -c "if [ ! -d node_modules ] || [ -z \"$(ls -A node_modules 2>/dev/null)\" ]; then npm ci; fi && npm run dev -- --host 0.0.0.0 --port 5173"
    depends_on:
      - api

  admin:
    image: node:22-alpine
    restart  : unless-stopped
    volumes  :
      - ./admin:/app
      - /app/node_modules
    working_dir: /app
    ports   :
      - 5174:5174
    networks:
      - mern-app
    command: sh -c "if [ ! -d node_modules ] || [ -z \"$(ls -A node_modules 2>/dev/null)\" ]; then npm ci; fi && npm run dev -- --host 0.0.0.0 --port 5174"
    depends_on:
      - api

volumes:
  mongo_data:
networks:
  mern-app:
    driver: bridge