name: mern-app

services:
  mongo:
    image: mongo:8.0.15
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - mern-app

  api:
    build:
      context    : ./backend
      dockerfile : Dockerfile
    restart  : unless-stopped
    env_file : ./backend/.env
    environment:
      - NODE_ENV=docker
    volumes  :
      - ./backend:/app/backend
      - /app/backend/node_modules
    command: sh -c "node config/import-data.js --delete && node config/import-data.js --import && npx nodemon server.js"
    ports:
      - 4000:4000
    networks:
      - mern-app
    depends_on:
      - mongo

  frontend:
    build:
      context    : ./frontend
      dockerfile : Dockerfile
    restart  : unless-stopped
    volumes  :
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    ports   :
      - 5173:5173
    networks:
      - mern-app
    command: npm run dev -- --host
    depends_on:
      - api

  admin:
    build:
      context    : ./admin
      dockerfile : Dockerfile
    restart  : unless-stopped
    volumes  :
      - ./admin:/app/admin
      - /app/admin/node_modules
    ports   :
      - 5174:5174
    networks:
      - mern-app
    command: npm run dev
    depends_on:
      - api

volumes:
  mongo_data:
networks:
  mern-app:
    driver: bridge