services:
  mongo:
    image: mongo:8.0
    # BỎ PORTS ĐỂ BẢO MẬT (Chỉ backend gọi được mongo nội bộ)
    # ports: 
    #   - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - mern-app

  api:
    image: ${DOCKERHUB_USERNAME}/backend:latest
    restart: unless-stopped
    env_file: ./backend/.env
    # Bỏ lệnh import data mỗi khi restart (nguy hiểm mất dữ liệu cũ)
    # Chỉ chạy server thôi
    command: node server.js 
    ports:
      - 4000:4000
    networks:
      - mern-app
    depends_on:
      - mongo

  frontend:
    image: ${DOCKERHUB_USERNAME}/frontend:latest
    restart: unless-stopped
    ports:
      - 5173:80 # Map cổng 5173 máy chủ vào cổng 80 của Nginx
    networks:
      - mern-app

  admin:
    image: ${DOCKERHUB_USERNAME}/admin:latest
    restart: unless-stopped
    ports:
      - 5174:80 # Map cổng 5174 máy chủ vào cổng 80 của Nginx
    networks:
      - mern-app

volumes:
  mongo_data:
networks:
  mern-app:
    driver: bridge